feat: Add Symfony HttpClient integration tests
php-vcr/php-vcr pull request #330
Opened 2020-11-15 18:22 UTC by pvgnd

### Context
php-vcr does not seems to work with Symfony HttpClient (#329). Here is the error:  
`RuntimeException: Unexpected error, could not find curl_getinfo in response or errors`

### What has been done

- Integration tests from guzzle have been duplicated for symfony/http-client in order to fix the issue

### How to test

- 

### Todo

- [ ] Find what is the issue and fix it

2020-11-16 21:52 UTC, aaa2000 commented
Maybe, you could apply the following PRs #285 #286 #294  to fix the issue

2020-11-18 11:53 UTC, JeroenVanOort requested changes
Could you please rebase your branch against the current master? I believe some things got mixed up during the years.

2020-11-18 11:53 UTC, JeroenVanOort commented on .gitignore
> +composer.lock
I don't remember why composer.lock is tracked, but I would suggest that it's removal is done in a separate PR.

2020-11-23 11:33 UTC, JeroenVanOort commented
Would you be so kind to rebase again? And some tests are still failing.

2020-11-23 12:20 UTC, pvgnd commented
Yes I'm trying to figure out what is the issue but can't make it work for now

2022-09-06 07:16 UTC, pvgnd commented
abandoned

2022-09-06 07:16 UTC, closed without merging